stages:
  data_ingestion:
    cmd: python src/bert_toxic/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bert_toxic/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.csv

  data_split:
    cmd: python src/bert_toxic/pipeline/stage_02_data_split.py
    deps:
      - src/bert_toxic/pipeline/stage_02_data_split.py
      - config/config.yaml
    params:
      - train_size
    outs:
      - artifacts/data_split/train/train.csv
      - artifacts/data_split/test/test.csv
    
  setup_model:
    cmd: python src/bert_toxic/pipeline/stage_03_setup_model.py
    deps:
      - src/bert_toxic/pipeline/stage_03_setup_model.py
      - config/config.yaml
    params:
      - classes
      - dropout
    outs:
      - artifacts/setup_model/model.pth

  train:
    cmd: python src/bert_toxic/pipeline/stage_04_train_model.py
    deps:
      - src/bert_toxic/pipeline/stage_04_train_model.py
      - config/config.yaml
      - artifacts/data_split/train/train.csv
      - artifacts/setup_model/model.pth
    params:
      - max_len
      - train_batch_size
      - epochs
      - learning_rate
      - train_num_workers
      - train_shuffle
    outs:
      - artifacts/training/model.pth

  evaluation:
    cmd: python src/bert_toxic/pipeline/stage_05_evaluate_model.py
    deps:
      - src/bert_toxic/pipeline/stage_05_evaluate_model.py
      - config/config.yaml
      - artifacts/data_split/test/test.csv
      - artifacts/training/model.pth
      - params.yaml
    metrics:
    - scores.json:
        cache: false

