stages:
  data_ingestion:
    cmd: python src/bert_toxic/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bert_toxic/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.csv
