train_size: 0.7

classes: 3
dropout: 0.3

max_len: 200
train_batch_size: 8
epochs: 0
learning_rate: 0.1
train_num_workers: 0
train_shuffle: true

valid_batch_size: 4
valid_num_workers: 0
valid_shuffle: true